config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index' 

  devise_for(:user, {
    class_name: 'Spree::User',
    singular: :spree_user,
    controllers: {
      sessions: 'user_sessions',
      registrations: 'user_registrations',
      passwords: 'user_passwords',
      confirmations: 'user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' }
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  resources :cart_line_items, only: :create

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, only: :show do
    resources :coupon_codes, only: :create
  end

  resource :cart, only: [:edit, :update] do
    put 'empty'
  end

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < StoreController
  helper 'spree/products', 'orders'

  respond_to :html

  before_action :store_guest_token
  before_action :assign_order, only: :update
  # note: do not lock the #edit action because that's where we redirect when we fail to acquire a lock
  around_action :lock_order, only: :update

  # Shows the current incomplete order from the session
  def edit
    @order = current_order(build_order_if_necessary: true)
    authorize! :edit, @order, cookies.signed[:guest_token]
    if params[:id] && @order.number != params[:id]
      flash[:error] = t('spree.cannot_edit_orders')
      redirect_to edit_cart_path
    end
  end

  def update
    authorize! :update, @order, cookies.signed[:guest_token]
    if @order.contents.update_cart(order_params)
      @order.next if params.key?(:checkout) && @order.cart?

      respond_with(@order) do |format|
        format.html do
          if params.key?(:checkout)
            redirect_to checkout_state_path(@order.checkout_steps.first)
          else
            redirect_to edit_cart_path
          end
        end
      end
    else
      respond_with(@order)
    end
  end

  def empty
    if @order = current_order
      authorize! :update, @order, cookies.signed[:guest_token]
      @order.empty!
    end

    redirect_to edit_cart_path
  end

  private

  def accurate_title
    t('spree.shopping_cart')
  end

  def store_guest_token
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
  end

  def order_params
    if params[:order]
      params[:order].permit(*permitted_order_attributes)
    else
      {}
    end
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = t('spree.order_not_found')
      redirect_to(root_path) && return
    end
  end

end

app/views/carts/_cart_adjustment.html.erb
<%
  type = local_assigns.fetch(:type, t('spree.adjustment'))
  label = local_assigns.fetch(:label, '')

  adjustments_sum = adjustments.sum(&:amount)
%>

<% if adjustments_sum != 0 %>
  <%= render(
    "carts/cart_amount_row",
    type: t('spree.tax'),
    label: label,
    amount: Spree::Money.new(adjustments_sum, currency: @order.currency)
  ) %>
<% end %>

app/views/carts/_cart_adjustments.html.erb
<div class="cart-adjustments" id="cart_adjustments">
  <%= render(
    "carts/cart_amount_row",
    type: t('spree.cart_subtotal', count: @order.line_items.sum(:quantity)),
    amount: @order.display_item_total
  ) %>

  <% if @order.line_item_adjustments.exists? %>
    <% @order.line_item_adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
      <% if adjustments.sum(&:amount) != 0 %>
        <%= render(
          "cart_adjustment",
          type: t('spree.promotion'),
          label: label,
          adjustments: adjustments
        ) %>
      <% end %>
    <% end %>
  <% end %>

  <% @order.all_adjustments.tax.eligible.group_by(&:label).each do |label, adjustments| %>
    <%= render(
      "carts/cart_adjustment",
      type: t('spree.tax'),
      label: label,
      adjustments: adjustments
    ) %>
  <% end %>

  <% @order.shipments.each do |shipment| %>
    <%= render(
      "carts/cart_amount_row",
      type: t('spree.shipping'),
      label: shipment.shipping_method.name,
      amount: shipment.display_total_before_tax
    ) %>
  <% end %>

  <% @order.adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
    <%= render(
      "carts/cart_adjustment",
      type: t('spree.adjustment'),
      label: label,
      adjustments: adjustments
    ) %>
  <% end %>
</div>

app/views/carts/_cart_amount_row.html.erb
<%
  type = local_assigns.fetch(:type, t('spree.adjustment'))
  label = local_assigns.fetch(:label, '')
%>

<div class="cart-amount-row">
  <dt>
    <span class="cart-amount-row__type"><%= type %>:</span>
    <span class="cart-amount-row__label"><%= label %></span>
  </dt>
  <dd class="cart-amount-row__amount"><%= amount %></dd>
</div>

app/views/carts/_cart_empty.html.erb
<header class="cart-empty">
  <h1 class="cart-empty__title">
    <%= t('spree.your_cart_is_empty') %>
  </h1>

  <p class="cart-empty__action">
    <%= link_to t('spree.continue_shopping'), products_path %>
  </p>
</header>

app/views/carts/_cart_footer.html.erb
<% order = order_form.object %>

<footer class="cart-footer">
  <p class="cart-footer__total">
    <%= t('spree.total') %>: <strong><%= order.display_total %></strong>
  </p>

  <div class="cart-footer__primary-action">
    <%= order_form.button(
      I18n.t('spree.checkout'),
      class: 'button-primary',
      id: 'checkout-link',
      name: :checkout
    ) %>
  </div>
</footer>

app/views/carts/_cart_header.html.erb
<header class="cart-header">
  <h1 class="cart-header__title">
    <%= t('spree.shopping_cart') %>
  </h1>

  <div class="cart-header__actions">
    <%= order_form.button(
      t("spree.update"),
      class: 'button-primary button-primary--bordered button-primary--small',
      id: 'update-button'
    ) %>
  </div>
</header>

app/views/carts/_cart_item.html.erb
<% variant = line_item.variant %>

<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <article class="cart-item">
    <div class="cart-item__image">
      <%= link_to(
        render(ImageComponent.new(
          image: variant.gallery.images.first || variant.product.gallery.images.first,
          size: :small
        )),
        variant.product
      ) %>
    </div>

    <%= render(
      'orders/item_info',
      line_item: line_item,
      variant: variant,
      classes: ['cart-item__info']
    ) %>

    <div class="cart-item__price-single">
      <%= line_item.single_money.to_html %>
    </div>

    <div class="cart-item__quantity">
      <div class="text-input">
        <%= item_form.text_field :quantity, type: 'number', min: 0 %>
      </div>
    </div>

    <div class="cart-item__price">
      <strong><%= line_item.display_amount.to_html unless line_item.quantity.nil? %></strong>
    </div>

    <div class="cart-item__remove">
      <%= order_form.submit(
        'Remove',
        class: 'delete',
        id: "delete_#{dom_id(line_item)}",
        data: { disable_with: 'Remove' }
      ) %>
    </div>
  </article>
<% end %>

app/views/carts/_cart_items.html.erb
<%
  order = order_form.object

  is_order_empty = (
    order.adjustments.nonzero.exists? ||
    order.line_item_adjustments.nonzero.exists? ||
    order.shipment_adjustments.nonzero.exists? ||
    order.shipments.any?
  )
%>

<section class="cart-items">
  <div class="cart-items-header">
    <h2 class="cart-items-header__title">Item</h2>
    <h2 class="cart-items-header__title">Price</h2>
    <h2 class="cart-items-header__title">Quantity</h2>
    <h2 class="cart-items-header__title">Subtotal</h2>
  </div>

  <%= render(
    partial: 'carts/cart_item',
    collection: order.line_items,
    as: :line_item,
    locals: { order_form: order_form }
  ) %>

  <% if is_order_empty %>
    <%= render 'carts/cart_adjustments' %>
  <% end %>
</section>

app/views/carts/_cart_secondary_actions.html.erb
<div class="cart-secondary-actions">
  <div class="cart-secondary-actions__continue">
    <%= link_to t('spree.continue_shopping'), products_path %>
  </div>

  <div class="cart-secondary-actions__empty">
    <%= form_tag empty_cart_path, method: :put do %>
      <%= button_tag(
        t('spree.empty_cart'),
        class: 'button-inline',
        name: :commit
      ) %>
    <% end %>
  </div>
</div>

app/views/carts/edit.html.erb
<% @body_id = 'cart' %>

<article class="cart-page">
  <% if @order.line_items.empty? %>
    <%= render 'carts/cart_empty' %>
  <% else %>
    <%= form_for @order, url: cart_path, html: {id: 'update-cart'} do |order_form| %>
      <% order = order_form.object %>
      <%= render 'carts/cart_header', order_form: order_form %>
      <%= render 'shared/error_messages', target: order %>
      <%= render 'carts/cart_items', order_form: order_form %>
      <%= render 'carts/cart_footer', order_form: order_form %>
    <% end %>

    <div class="cart-page__other-actions">
      <%= render 'carts/cart_secondary_actions' %>

      <div class="cart-page__coupon-code">
        <%= render 'orders/coupon_code' %>
      </div>
    </div>
  <% end %>
</article>